# Generated by Django 5.0.7 on 2024-08-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nuip', models.IntegerField()),
                ('cardNumber', models.IntegerField()),
                ('cardExpiration', models.DateField()),
                ('cardCVV', models.IntegerField(max_length=3)),
            ],
        ),
    ]
