# Generated by Django 5.0.7 on 2024-08-28 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaapp', '0004_alter_metodopago_cardcvv_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imagen',
        ),
    ]
