# Generated by Django 5.0.7 on 2024-08-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaapp', '0005_delete_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
