# Generated by Django 5.0.7 on 2024-08-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaapp', '0007_pedidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
