# Generated by Django 5.0.7 on 2024-08-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaapp', '0008_alter_pedidos_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodopago',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
